# _config.yml
title: Your Personal Blog Title
description: A place for my articles.
# remote_theme: pages-themes/architect@v0.2.0
# plugins:
# - jekyll-remote-theme
theme: minima # A standard, built-in Jekyll theme